### ISSUE TITLE
[suggestion] only replace crops with seeds of their own type

### ISSUE THREAD

**Issue by CodeF53** [LordMZTE/quickreplant#1]
If attempting to harvest a field consisting of wheat and potatoes, the mod will replace potatoes with wheat seeds!

Ideally, it would only plant potatoes where potatoes are, and wheat seed where wheat is.

**Comment by LordMZTE** [comment]
This is an intended feature. The mod always uses the seed in your hand to replant the crops, no matter the type. I think this is useful in case you do want to change the crop to different ones, and also I wouldn't be sure how to implement this either. Do you want it to just not replace the crop if youre holding a different seed? Should it switch the selected hotbar slot to the correct seed? But this would also get rid of the functionality of being able to use a different crop type. I think it's good the way it is right now.
