### ISSUE TITLE
Game Crashes when placing a door. [1.19]

### ISSUE THREAD

**Issue by NicoTheCinderace** [LordMZTE/quickreplant#7]
Here's my crash report: [crash-2022-06-20_18.04.48-client.txt](https://github.com/LordMZTE/quickreplant/files/8943929/crash-2022-06-20_18.04.48-client.txt)

Whenever I attempt to place down a door of any kind with this mod, it just crashes for some reason. 

Something about Fabric Events Interaction v0 is mentioned, so I'm not sure what's going on.

**Comment by LordMZTE** [comment]
This has been fixed in version 1.1.1. Please update.
