### ISSUE TITLE
Update quickreplant 1.19.4

### ISSUE THREAD

**Issue by QueenUlyana** [LordMZTE/quickreplant#8]
@LordMZTE  Please update quickreplant to version 1.19.4 Fabric. I really like your mod.

**Comment by LordMZTE** [comment]
My mods will not be ported to versions >= 1.19.

I disagree with where the game is going with chat signing and stuff as well as the way how micro~~shit~~soft manages the game. I might be doing a backport some day, who knows.

The mod is open source and very simple, it'd be easy to port yourself

**Comment by QueenUlyana** [comment]
> The mod is open source and very simple, it'd be easy to port yourself

If it were easy for me, I wouldn't bother you.
