### ISSUE TITLE
Please update your mod to Minecraft version 1.20.

### ISSUE THREAD

**Issue by surfishs** [LordMZTE/quickreplant#9]
Please update your mod to Minecraft version 1.20.
I see you spouting mojang inaction crap updates.
I am equally disgusted by this meaningless update content, mojang simply does not know what is Minecraft.
However, I don't think this is a reason to choose to abandon the latest version.
We can totally use mods to roll back mojang updates, just like most mods already do, no?

**Comment by LordMZTE** [comment]
Why choose to take new versions and remove the malware and not just use older versions which work equally as well and have less bloat content? It just makes no sense to even touch the wreck microsoft has created.

As I've said in #8: you're free to port the mod yourself, I won't be doing so.
